name: Deploy to Amazon ECS
on:
  push:
    branches:
      - master
      - 'feature/**'

env:
  AWS_REGION: ap-southeast-1                   # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: shared-advanceph.app.ecr         # set this to your Amazon ECR repository name
  ECS_SERVICE: staging-advancetechph-service                 # set this to your Amazon ECS service name
  ECS_CLUSTER: staging-advancetechph-cluster                 # set this to your Amazon ECS cluster name

  CONTAINER_NAME: advancetechph           # set this to the name of the container in the
                                              # containerDefinitions section of your task definition

defaults:
  run:
    shell: bash

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
    - id: step1
      run: echo "::set-output name=test::hello"
    - id: step2
      run: echo "::set-output name=test::world"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}